// src/pages/vue-test/multiton-demo/multiton-lv5/components/merchant-search/merchant-search.vue
<template>
  <div>
    <a-card style="margin-bottom: 24px">
      <a-form layout="inline" :model="searchState">
        <a-form-item label="商户名称">
          <a-input v-model:value="searchState.name" placeholder="请输入商户名" allow-clear />
        </a-form-item>
        <a-form-item label="行业类型">
          <a-select
            v-model:value="searchState.category"
            placeholder="请选择"
            style="width: 150px"
            allow-clear
          >
            <a-select-option v-for="opt in categoryOptions" :key="opt.value" :value="opt.value">
              {{ opt.label }}
            </a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item>
          <a-button type="primary" @click="all_event_pipeline.other.search()">查询</a-button>
          <a-button style="margin-left: 8px" @click="all_event_pipeline.other.reset()">
            重置</a-button
          >
        </a-form-item>
      </a-form>
    </a-card>

    <!-- 2. 操作栏 -->
    <div
      style="
        margin-bottom: 16px;
        display: flex;
        justify-content: space-between;
        align-items: center;
      "
    >
      <a-button type="primary" size="large" @click="all_event_pipeline.other.handleAdd()">
        <template #icon><plus-outlined /></template>
        入驻新商户
      </a-button>
      <span style="color: #999">当前共 {{ pagination.total }} 家商户</span>
    </div>
  </div>
</template>

<script setup>
import { PlusOutlined } from '@ant-design/icons-vue'
import { all_singleton } from '../../state/singleton.js'
import * as all_config from '../../state/config.js'
import { all_event_pipeline } from '../../module/event-pipeline/event-pipeline.js'
const { categoryOptions } = all_config
const { searchState, pagination } = all_singleton
</script>

// project/react-test-app/pages/multiton-demo/components/MerchantSearch.jsx
import { CATEGORY_OPTIONS } from '../data/merchant-data'
import { Input, Select, Button, Space, Card, Typography } from 'antd'

const { Text } = Typography

/**
 * 多例模式 - 共享搜索组件
 *
 * 纯受控组件，通过 props 接收状态和操作函数
 * 可被多个实例复用，对标 Vue 侧 merchant-search
 */
export default function MerchantSearch({
  searchState,
  onSearchChange,
  onSearch,
  onReset,
  onAdd,
  total,
}) {
  return (
    <div>
      <Card style={{ marginBottom: 16 }}>
        <Space wrap size="middle">
          <Space>
            <span>商户名称</span>
            <Input
              style={{ width: 160 }}
              value={searchState.name}
              onChange={(e) => onSearchChange({ ...searchState, name: e.target.value })}
              placeholder="请输入商户名"
            />
          </Space>
          <Space>
            <span>行业类型</span>
            <Select
              style={{ width: 140 }}
              value={searchState.category}
              onChange={(value) => onSearchChange({ ...searchState, category: value })}
              options={[{ value: '', label: '全部' }, ...CATEGORY_OPTIONS]}
            />
          </Space>
          <Button type="primary" onClick={onSearch}>
            查询
          </Button>
          <Button onClick={onReset}>重置</Button>
        </Space>
      </Card>

      <div
        style={{
          marginBottom: 16,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <Button type="primary" size="large" onClick={onAdd}>
          + 入驻新商户
        </Button>
        <Text type="secondary">当前共 {total} 家商户</Text>
      </div>
    </div>
  )
}
