// src/pages/vue-test/singleton-demo/singleton-lv4/components/UserTable.vue
<template>
  <a-table
    :columns="columns"
    :data-source="tableData"
    :loading="loading"
    :pagination="pagination"
    @change="(pag) => mitt_emit('handleTableChange', pag)"
    row-key="id"
    bordered
  >
    <template #bodyCell="{ column, record }">
      <template v-if="column.key === 'status'">
        <a-tag :color="record.status === '1' ? 'green' : 'red'">
          {{ record.status === '1' ? '启用' : '禁用' }}
        </a-tag>
      </template>
      <template v-else-if="column.key === 'action'">
        <a @click="mitt_emit('handleEdit', record)">编辑</a>
        <a-divider type="vertical" />
        <a-popconfirm title="确定要删除该用户吗？" @confirm="mitt_emit('handleDelete', record.id)">
          <a style="color: #ff4d4f">删除</a>
        </a-popconfirm>
      </template>
    </template>
  </a-table>
</template>

<script setup>
import { columns } from '../config/config.js'
import * as all_singleton from '../variable/singleton.js'
import {  mitt_emit} from "../mitt/mitt-emit.js"
const { tableData, loading, pagination } = all_singleton
defineProps({})
 
</script>

<style scoped>
:deep(.ant-table-pagination) {
  margin: 16px 0 !important;
}
</style>

// project/react-test-app/pages/singleton-demo/components/UserTable.jsx
import { useUserContext } from '../context/UserContext'
import { TABLE_COLUMNS } from '../data/user-data'
import { Table, Tag, Button, Popconfirm, Space, Typography } from 'antd'

const { Text } = Typography

/**
 * 单例模式 - 表格组件
 *
 * 通过 Context 消费表格数据和操作管道
 */
export default function UserTable() {
  const {
    tableData,
    filteredData,
    loading,
    pagination,
    handlePageChange,
    handleEdit,
    handleDelete,
  } = useUserContext()

  const columns = TABLE_COLUMNS.map((col) => {
    if (col.key === 'status') {
      return {
        ...col,
        render: (_, record) =>
          record.status === '1' ? <Tag color="success">启用</Tag> : <Tag color="error">禁用</Tag>,
      }
    }
    if (col.key === 'action') {
      return {
        ...col,
        render: (_, record) => (
          <Space>
            <a onClick={() => handleEdit(record)}>编辑</a>
            <Popconfirm
              title="确定要删除该用户吗？"
              onConfirm={() => handleDelete(record.id)}
              okText="确定"
              cancelText="取消"
            >
              <a style={{ color: '#ff4d4f' }}>删除</a>
            </Popconfirm>
          </Space>
        ),
      }
    }
    return col
  })

  return (
    <Table
      columns={columns}
      dataSource={tableData}
      rowKey="id"
      loading={loading}
      pagination={{
        current: pagination.current,
        pageSize: pagination.pageSize,
        total: filteredData.length,
        showTotal: (total) => `共 ${total} 条`,
        onChange: (page, pageSize) => handlePageChange(page, pageSize),
      }}
      size="middle"
    />
  )
}
